# Generated by Django 5.2.7 on 2025-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
