# Generated by Django 5.2.7 on 2025-11-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehiculo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion',
        ),
    ]
