# Generated by Django 5.2.7 on 2025-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('combustible', models.CharField(default='Gasolina', max_length=50)),
                ('asientos', models.CharField(default='5', max_length=20)),
            ],
            options={
                'db_table': 'automoviles',
            },
        ),
    ]
